package com.bitsycore.ktc.codegen

import com.bitsycore.ktc.ast.Expr

/*
Miscellaneous pure utilities used throughout C code emission.
No CCodeGen state is required unless noted.
*/

/* Escape a single character for use inside a C character literal (single-quoted). */
internal fun escapeC(inChar: Char): String = when (inChar) {
    '\''     -> "\\'"
    '\\'     -> "\\\\"
    '\n'     -> "\\n"
    '\t'     -> "\\t"
    '\r'     -> "\\r"
    '\u0000' -> "\\0"
    else     -> inChar.toString()
}

/* Escape a string for use inside a C string literal (double-quoted). */
internal fun escapeStr(inStr: String): String = inStr
    .replace("\\", "\\\\")
    .replace("\"", "\\\"")
    .replace("\n", "\\n")
    .replace("\t", "\\t")
    .replace("\r", "\\r")

/*
Evaluate an expression and immediately flush any accumulated pre-statements.
Use before every control-flow keyword (if/while/do-while condition) so that
struct wrapper declarations generated by genExpr land before the keyword, not
inside the condition expression itself.
*/
internal fun CCodeGen.genExprFlushed(inExpr: Expr, inInd: String): String {
    val vResult = genExpr(inExpr) // evaluate — may populate preStmts
    flushPreStmts(inInd)          // emit any hoisted declarations before the keyword
    return vResult
}
