package com.bitsycore.ktc.codegen

import com.bitsycore.ktc.ast.Expr
import com.bitsycore.ktc.ast.TypeRef
import com.bitsycore.ktc.codegen.expr.genExpr

/*
Miscellaneous pure utilities used throughout C code emission.
No CCodeGen state is required unless noted.
*/

/* Escape a single character for use inside a C character literal (single-quoted). */
internal fun escapeC(inChar: Char): String = when (inChar) {
    '\''     -> "\\'"
    '\\'     -> "\\\\"
    '\n'     -> "\\n"
    '\t'     -> "\\t"
    '\r'     -> "\\r"
    '\u0000' -> "\\0"
    else     -> inChar.toString()
}

/* Escape a string for use inside a C string literal (double-quoted). */
internal fun escapeStr(inStr: String): String = inStr
    .replace("\\", "\\\\")
    .replace("\"", "\\\"")
    .replace("\n", "\\n")
    .replace("\t", "\\t")
    .replace("\r", "\\r")

/*
Evaluate an expression and immediately flush any accumulated pre-statements.
Use before every control-flow keyword (if/while/do-while condition) so that
struct wrapper declarations generated by genExpr land before the keyword, not
inside the condition expression itself.
*/
/**
 * Execute [block] with [typeSubst] temporarily replaced by [newSubst].
 * Restores the previous substitution afterwards.
 * No-op (just calls block) when [newSubst] is null or empty.
 */
internal inline fun <T> CCodeGen.withTypeSubst(newSubst: Map<String, String>?, block: () -> T): T {
    if (newSubst.isNullOrEmpty()) return block()
    val saved = typeSubst
    typeSubst = newSubst
    val result = block()
    typeSubst = saved
    return result
    }

/* Finish a C function body: pop scope, restore function state, emit closing brace and blank line. */
internal fun CCodeGen.closeFunBody(inPrevState: CCodeGen.FunState) {
    popScope()
    restoreFunState(inPrevState)
    impl.appendLine("}")
    impl.appendLine()
    }

/* Evaluate an expression with a heapAllocTargetType hint set, then clear the hint. */
internal fun CCodeGen.genExprWithHeapTarget(expr: Expr, targetType: TypeRef?): String {
    heapAllocTargetType = targetType
    val result = genExpr(expr)
    heapAllocTargetType = null
    return result
    }

internal fun CCodeGen.genExprFlushed(inExpr: Expr, inInd: String): String {
    val vResult = genExpr(inExpr) // evaluate — may populate preStmts
    flushPreStmts(inInd)          // emit any hoisted declarations before the keyword
    return vResult
}
