name = "ktc.-SDL3"
version = "3.x"
description = "SDL3 (Simple DirectMedia Layer 3) Kotlin bindings for KTC"
authors = ["bitsycore"]
license = "MIT"
url = "https://github.com/bitsycore/KotlinToC"
repository = "https://github.com/bitsycore/KotlinToC.git#src/main/resources/modules/SDL3"
dependencies = ["ktc.std"]